version: '3.8'
services:
  angular-app:
    build:
      context: ./luxuryproducts-frontend
    ports:
      - "4200:80"
    depends_on:
      - springboot-app

  springboot-app:
    build:
      context: ./luxuryproducts-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/todo_app_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: todo_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
